// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "integration_test/model/entity"

	mock "github.com/stretchr/testify/mock"
)

// QuoteRepoInterface is an autogenerated mock type for the QuoteRepoInterface type
type QuoteRepoInterface struct {
	mock.Mock
}

// Insert provides a mock function with given fields: ctx, quote
func (_m *QuoteRepoInterface) Insert(ctx context.Context, quote entity.Quote) error {
	ret := _m.Called(ctx, quote)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Quote) error); ok {
		r0 = rf(ctx, quote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewQuoteRepoInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewQuoteRepoInterface creates a new instance of QuoteRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQuoteRepoInterface(t mockConstructorTestingTNewQuoteRepoInterface) *QuoteRepoInterface {
	mock := &QuoteRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
